# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2019

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  首页: /
  要闻: /categories/yaowen
  时政: /categories/shizheng
  科技: /categories/keji
  军事: /categories/junshi
  财经: /categories/caijing
  体育: /categories/tiyu
  娱乐: /categories/yule
  教育: /categories/jiaoyu
  其它: /categories/qita


# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>testing...</p>
widget:
  Tags: false
  Categories: true
  Custom: true

widget_custom:
    title: 热词
    content:
      <ul>
        <li class="category-list-item">
          <a class="category-list-link" href="#">服务</a>
          <span class="category-list-count">128</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">信息</a>
          <span class="category-list-count">121</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">平台</a>
          <span class="category-list-count">112</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">中国</a>
          <span class="category-list-count">106</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">号系</a>
          <span class="category-list-count">100</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">美国</a>
          <span class="category-list-count">85</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">国家</a>
          <span class="category-list-count">76</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">影响</a>
          <span class="category-list-count">65</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">工作</a>
          <span class="category-list-count">59</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">经济</a>
          <span class="category-list-count">54</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">公司</a>
          <span class="category-list-count">54</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">企业</a>
          <span class="category-list-count">50</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">发展</a>
          <span class="category-list-count">45</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">世界</a>
          <span class="category-list-count">44</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">北京</a>
          <span class="category-list-count">43</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">未来</a>
          <span class="category-list-count">41</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">首次</a>
          <span class="category-list-count">39</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">全球</a>
          <span class="category-list-count">39</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">政府</a>
          <span class="category-list-count">38</span>
          &nbsp;&nbsp;
          <a class="category-list-link" href="#">国际</a>
          <span class="category-list-count">38</span>
          &nbsp;&nbsp;
        </li>
      </ul>


# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  fancybox: false

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics:

# Duoshuo
duoshuo_shortname:
# Disqus
disqus_shortname:


# ===========================================
# Version
# ===========================================
version: 1.1
